# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

[aws]
format = 'on [$symbol($profile )(\($region\) )(\[$duration\] )]($style)'
symbol = '☁️ '

[dotnet]
detect_files = ["global.json", "Directory.Build.props", "Directory.Build.targets", "Packages.props"]

[memory_usage]
disabled = false
